/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form_master;

import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 */
public class Form_6_Pengembalian extends javax.swing.JDialog {
    private final DefaultTableModel tabel;
    Boolean fungsi_simpan=false, fungsi_ubah=false;
    public Statement stt;
    public Connection con;
    private TableColumn column;

    /**
     * Creates new form Form_1_Kategori
     */
    public Form_6_Pengembalian(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String[] judul={"No Induk Buku","Judul Buku","Pengarang","Batas Pengembalian","Tanggal Kembali","Denda"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        aturKolom();        
        aturFokus();
        tampil_no_peminjaman();
        ImageIcon ico = new ImageIcon("src/gambar/icon_item.png");
        setIconImage(ico.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nis = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_no_telp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_kelas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_judul_buku = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_pengarang = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_batas_pengembalian = new javax.swing.JTextField();
        tf_denda = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tf_total_denda = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tf_nib = new javax.swing.JComboBox();
        tf_no_peminjaman = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_tanggal_kembali = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Pengembalian");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NIS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 141, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama Anggota");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 177, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 178, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText(":");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 141, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(":");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 104, -1, -1));

        tf_nis.setEditable(false);
        tf_nis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_nis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_nis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_nis.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 134, 220, 30));

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(17);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 283, 1021, 159));

        tambah.setText("Tambah");
        tambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 239, 87, 37));

        simpan.setText("Simpan");
        simpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        simpan.setBorderPainted(false);
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.setIconTextGap(2);
        simpan.setMargin(new java.awt.Insets(2, 0, 2, 0));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 452, 87, 37));

        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.setIconTextGap(1);
        hapus.setMargin(new java.awt.Insets(2, 0, 2, 0));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 452, 87, 37));

        refresh.setText("Refresh");
        refresh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 452, 87, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MASTER PENGEMBALIAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 35, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("No Peminjaman");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 104, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("APLIKASI PERPUSTAKAAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 14));

        tf_nama.setEditable(false);
        tf_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_nama.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 170, 220, 30));

        tf_no_telp.setEditable(false);
        tf_no_telp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_no_telp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_no_telp.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 242, 220, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("No Telepon");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 248, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 248, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 213, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Kelas");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 213, -1, -1));

        tf_kelas.setEditable(false);
        tf_kelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_kelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_kelas.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 206, 220, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("No Induk Buku");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 104, -1, -1));

        tf_judul_buku.setEditable(false);
        tf_judul_buku.setColumns(20);
        tf_judul_buku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_judul_buku.setRows(5);
        tf_judul_buku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jScrollPane1.setViewportView(tf_judul_buku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 134, 220, 98));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(":");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 104, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Judul Buku");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 142, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Pengarang");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 248, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText(":");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 248, -1, -1));

        tf_pengarang.setEditable(false);
        tf_pengarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_pengarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_pengarang.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 242, 220, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText(":");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 142, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Batas Pengembalian");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 104, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText(":");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 104, -1, -1));

        tf_batas_pengembalian.setEditable(false);
        tf_batas_pengembalian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_batas_pengembalian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_batas_pengembalian.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_batas_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 98, 100, 30));

        tf_denda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_denda.setText("0");
        tf_denda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_denda.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 170, 100, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText(":");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 141, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Tanggal Kembali");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 141, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText(":");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 458, -1, -1));

        tf_total_denda.setEditable(false);
        tf_total_denda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_total_denda.setText("0");
        tf_total_denda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_total_denda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_total_denda.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_total_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 452, 150, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Total Denda");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 458, -1, -1));

        tf_nib.setEditable(true);
        tf_nib.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        tf_nib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nibActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nib, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 98, 220, 30));

        tf_no_peminjaman.setEditable(true);
        tf_no_peminjaman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        tf_no_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_no_peminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(tf_no_peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 98, 220, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Denda");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 177, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText(":");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 177, -1, -1));

        tf_tanggal_kembali.setEditable(false);
        tf_tanggal_kembali.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tanggal_kembali.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_tanggal_kembali.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_tanggal_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 134, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon7.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 70, 64));

        keluar.setText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 452, 87, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Form Master 2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        boolean data_ganda=false;
        int data = jTable1.getRowCount();
        for(int i=0;i<data;i++){
            if(tabel.getValueAt(i, 0).equals(tf_nib.getSelectedItem())){
                data_ganda = true;
            }
        }
        
        if(data_ganda){
            JOptionPane.showMessageDialog(null, "Data Sudah Dimasukkan Dalam Daftar !");
        }else{
            if(tf_nama.getText().isEmpty()){
                tf_no_peminjaman.requestFocus();
            }else{
                if(tf_judul_buku.getText().isEmpty()){
                    tf_nib.requestFocus();
                }else{
                    String[] tabel_master={tf_nib.getSelectedItem().toString(),tf_judul_buku.getText(),tf_pengarang.getText(),tf_batas_pengembalian.getText(),tf_tanggal_kembali.getText(),tf_denda.getText()};
                    tabel.addRow(tabel_master);

                    tf_nib.setSelectedItem("-");
                    tf_judul_buku.setText(null);
                    tf_pengarang.setText(null);
                    tf_batas_pengembalian.setText(null);
                    tf_tanggal_kembali.setText(null);
                    tf_denda.setText("0");
                    
                    hitung_total_denda();
                }
            }
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void tf_no_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_no_peminjamanActionPerformed
        tampil_data_peminjaman();
        tf_batas_pengembalian.setText(null);
        tf_tanggal_kembali.setText(null);
        tf_denda.setText("0");
    }//GEN-LAST:event_tf_no_peminjamanActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        empty_field();
        tf_no_peminjaman.setSelectedItem("-");
    }//GEN-LAST:event_refreshActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        int data = jTable1.getRowCount();
        if(tf_nama.getText().isEmpty() || data == 0){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Pengembalian Terlebih Dahulu !");
        }else{
            fungsi_simpan_data();
            fungsi_update_jumlah_buku_dan_status();
            refreshActionPerformed(evt);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tf_nibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nibActionPerformed
        tampil_data_detil_peminjaman();        
    }//GEN-LAST:event_tf_nibActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int tabel_data = jTable1.getSelectedRow();        
        if(String.valueOf(tabel_data).equals("-1")){
            JOptionPane.showMessageDialog(this, "Pilih Daftar Yang Akan Dihapus !");
        }else
        {
            tabel.removeRow(tabel_data);
            tf_nib.requestFocus();
        }
        hitung_total_denda();
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_6_Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_6_Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_6_Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_6_Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_6_Pengembalian dialog = new Form_6_Pengembalian(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton refresh;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tf_batas_pengembalian;
    private javax.swing.JTextField tf_denda;
    private javax.swing.JTextArea tf_judul_buku;
    private javax.swing.JTextField tf_kelas;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JComboBox tf_nib;
    private javax.swing.JTextField tf_nis;
    private javax.swing.JComboBox tf_no_peminjaman;
    private javax.swing.JTextField tf_no_telp;
    private javax.swing.JTextField tf_pengarang;
    private javax.swing.JTextField tf_tanggal_kembali;
    private javax.swing.JTextField tf_total_denda;
    // End of variables declaration//GEN-END:variables
    
    private void empty_field() {        
        tf_no_peminjaman.setSelectedItem("-");
        tf_nis.setText(null);
        tf_nama.setText(null);
        tf_kelas.setText(null);
        tf_no_telp.setText(null);
        tf_nib.setSelectedItem("-");
        tf_judul_buku.setText(null);
        tf_pengarang.setText(null);
        tf_batas_pengembalian.setText(null);
        tf_tanggal_kembali.setText(null);
        tf_denda.setText("0");
        tf_total_denda.setText("0");
        
        int data = jTable1.getRowCount();
        for(int i=0;i<data;i++){
            tabel.removeRow(0);
        }
    }
    
    private void tampil_no_peminjaman() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_4_transaksi_peminjaman ORDER BY no_peminjaman DESC");
            while(re.next()){
                tf_no_peminjaman.addItem(re.getString("no_peminjaman"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan Tampil No Pengembalian !");
        }
    }
    
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }

    private void fungsi_simpan_data() {
        boolean simpan_transaksi=false, simpan_detil=false;
        SimpleDateFormat sdfdate = new SimpleDateFormat("yyyy-MM-dd");
        Date tanggal_sekarang = new Date();
        try {
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            koneksi.createStatement().executeUpdate("INSERT INTO tbl_6_transaksi_pengembalian VALUES('"+tf_no_peminjaman.getSelectedItem()+"'"
            + ",'"+tf_nis.getText()+"','"+sdfdate.format(tanggal_sekarang)+"','"+tf_total_denda.getText()+"')");
            simpan_transaksi = true;
        } catch (SQLException ex) {
            simpan_transaksi = false;
        }
        
        int jumlah_data = jTable1.getRowCount();
        for(int i=0;i<jumlah_data;i++){
            try {
                Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
                koneksi.createStatement().executeUpdate("INSERT INTO tbl_7_detil_pengembalian VALUES('"+tf_no_peminjaman.getSelectedItem()+"'"
                + ",'"+tabel.getValueAt(i, 0)+"','1','"+tabel.getValueAt(i, 4)+"','"+tabel.getValueAt(i, 5)+"')");
                simpan_detil = true;
            } catch (SQLException ex) {
                simpan_detil = false;
            }
        }
        
        if(simpan_transaksi && simpan_detil){
            JOptionPane.showMessageDialog(null, "Data Pengembalian Disimpan");
        }else{
            JOptionPane.showMessageDialog(null, "Data Pengembalian Gagal Disimpan");
            if(simpan_detil == false){
                JOptionPane.showMessageDialog(null, "Simpan Detil Gagal");
            }else
            if(simpan_transaksi == false){
                JOptionPane.showMessageDialog(null, "Simpan Transaksi Gagal");
            }else{
                JOptionPane.showMessageDialog(null, "Simpan Gagal");
            }
        }
    }

    private void aturKolom() {
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(110);        
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(315); 
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(200);
        column = jTable1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(130);
        column = jTable1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(130);
        column = jTable1.getColumnModel().getColumn(5); 
        column.setPreferredWidth(130);
    }

    private void aturFokus() {
        tf_no_peminjaman.setNextFocusableComponent(tf_nib);
        tf_nib.setNextFocusableComponent(tf_no_peminjaman);
    }
    
    private void tampilTanggal() {
        SimpleDateFormat sdfdate = new SimpleDateFormat("yyyy-MM-dd");
        Date tanggal_sekarang = new Date();
        tf_total_denda.setText(sdfdate.format(tanggal_sekarang));
        
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, 6);
        Date tigaharilagi = cal.getTime();
        tf_batas_pengembalian.setText(sdfdate.format(tigaharilagi));
    }

    private void tampil_data_peminjaman() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_4_transaksi_peminjaman WHERE no_peminjaman = '"+tf_no_peminjaman.getSelectedItem()+"'");
            while(re.next()){                
                ResultSet re1=koneksi.createStatement().executeQuery("SELECT * FROM tbl_2_anggota WHERE nis = '"+re.getString("nis")+"'");
                while(re1.next()){
                    tf_nis.setText(re1.getString(1));
                    tf_nama.setText(re1.getString(2));
                    tf_kelas.setText(re1.getString(3));
                    tf_no_telp.setText(re1.getString(4));
                }
                
                ResultSet re2=koneksi.createStatement().executeQuery("SELECT * FROM tbl_5_detil_peminjaman WHERE no_peminjaman = '"+tf_no_peminjaman.getSelectedItem()+"' AND status = 'Dipinjam'");
                tf_nib.removeAllItems();
                tf_nib.addItem("-");
                while(re2.next()){
                    tf_nib.addItem(re2.getString(2));
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan Tampil Data Pengembalian !");
        }
    }

    private void tampil_data_detil_peminjaman() {
        BigDecimal denda_perhari;
        denda_perhari = new BigDecimal("0");
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_3_buku WHERE no_induk_buku = '"+tf_nib.getSelectedItem()+"'");
            while(re.next()){
                tf_judul_buku.setText(re.getString(3));
                tf_pengarang.setText(re.getString(4));
            }
            
            ResultSet re1=koneksi.createStatement().executeQuery("SELECT * FROM tbl_4_transaksi_peminjaman WHERE no_peminjaman = '"+tf_no_peminjaman.getSelectedItem()+"'");
            while(re1.next()){
                tf_batas_pengembalian.setText(re1.getString("batas_pengembalian"));
            }
            
            ResultSet re2=koneksi.createStatement().executeQuery("SELECT * FROM tbl_9_denda");
            while(re2.next()){
                denda_perhari = new BigDecimal(re2.getString("denda_perhari"));
            }
            
            //Hitung Keterlambatan dan Denda
            SimpleDateFormat sdfdate = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal_sekarang = new Date();
            tf_tanggal_kembali.setText(sdfdate.format(tanggal_sekarang));
            
            try{
                if(tf_tanggal_kembali.getText().isEmpty() || tf_batas_pengembalian.getText().isEmpty()){
                    
                }else{
                    SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
                    Date tanggal_batas_pengembalian = (Date) date.parse(tf_batas_pengembalian.getText());
                    Date tanggal_kembali = (Date) date.parse(tf_tanggal_kembali.getText());                
                    if(tanggal_kembali.getTime() > tanggal_batas_pengembalian.getTime()){
                        long Telat = Math.abs(tanggal_kembali.getTime() - tanggal_batas_pengembalian.getTime());
                        long jumlah_hari_telat = TimeUnit.MILLISECONDS.toDays(Telat);
                        BigDecimal denda_perbuku = denda_perhari.multiply(new BigDecimal(jumlah_hari_telat));
                        tf_denda.setText(""+denda_perbuku);
                    }
                }                                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error Hitung Denda !");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan Tampil Data Buku !");
        }
    }

    private void fungsi_update_jumlah_buku_dan_status() {
        int jumlah_data = jTable1.getRowCount();
        for(int i=0;i<jumlah_data;i++){
            int jumlah_buku=0, tersedia=0, keluar=0;
            try {
                com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
                ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_3_buku WHERE no_induk_buku = '"+tabel.getValueAt(i, 0)+"'");
                while(re.next()){
                    jumlah_buku = Integer.parseInt(re.getString("jumlah"));
                    keluar = Integer.parseInt(re.getString("keluar")) - 1;
                    tersedia = jumlah_buku - keluar;
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan Tampil Baca Data Jumlah Buku !");
            }
            
            try {
                Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
                koneksi.createStatement().executeUpdate("UPDATE tbl_3_buku SET jumlah='"+jumlah_buku+"',tersedia='"+tersedia+"',keluar='"+keluar+"' "
                + "WHERE no_induk_buku = '"+tabel.getValueAt(i, 0)+"'");
            } catch (SQLException ex1) {
               JOptionPane.showMessageDialog(this, "Data Jumlah Gagal Diubah !");
            }
            
            try {
                Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
                koneksi.createStatement().executeUpdate("UPDATE tbl_5_detil_peminjaman SET status='Kembali' WHERE no_induk_buku = '"+tabel.getValueAt(i, 0)+"' AND no_peminjaman = '"+tf_no_peminjaman.getSelectedItem()+"'");
            } catch (SQLException ex1) {
               JOptionPane.showMessageDialog(this, "Data Jumlah Gagal Diubah !");
            }
        }
    }

    private void hitung_total_denda() {
        int data = 0;
        data = jTable1.getRowCount();
        BigDecimal total_denda, denda;
        total_denda = new BigDecimal("0");
        for(int i=0;i<data;i++){
            denda = new BigDecimal(tabel.getValueAt(i, 5).toString());
            total_denda = total_denda.add(denda);
        }
        tf_total_denda.setText(""+total_denda);
    }
}
