/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form_master;

import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 */
public class Form_5_Peminjaman extends javax.swing.JDialog {
    private final DefaultTableModel tabel;
    Boolean fungsi_simpan=false, fungsi_ubah=false;
    public Statement stt;
    public Connection con;
    private TableColumn column;

    /**
     * Creates new form Form_1_Kategori
     */
    public Form_5_Peminjaman(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String[] judul={"No Induk Buku","Judul Buku","Pengarang","Jumlah Buku","Tersedia","Keluar"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        aturKolom();        
        aturFokus();
        penomoran_otomatis();
        tampil_nis_dan_nib();
        tampilTanggal();
        ImageIcon ico = new ImageIcon("src/gambar/icon_item.png");
        setIconImage(ico.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_no_peminjaman = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_no_telp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_kelas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_judul_buku = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_pengarang = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_jumlah_buku = new javax.swing.JTextField();
        tf_tersedia = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_keluar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tf_tanggal_pinjam = new javax.swing.JTextField();
        tf_batas_pengembalian = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tf_jumlah_buku_dipinjam = new javax.swing.JTextField();
        tf_nib = new javax.swing.JComboBox();
        tf_nis = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Peminjaman");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NIS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 141, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama Anggota");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 177, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 178, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText(":");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 141, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(":");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 104, -1, -1));

        tf_no_peminjaman.setEditable(false);
        tf_no_peminjaman.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_no_peminjaman.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_no_peminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_no_peminjaman.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_no_peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 98, 220, 30));

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(17);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 283, 1021, 159));

        tambah.setText("Tambah");
        tambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 239, 87, 37));

        simpan.setText("Simpan");
        simpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        simpan.setBorderPainted(false);
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.setIconTextGap(2);
        simpan.setMargin(new java.awt.Insets(2, 0, 2, 0));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 452, 87, 37));

        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.setIconTextGap(1);
        hapus.setMargin(new java.awt.Insets(2, 0, 2, 0));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 452, 87, 37));

        refresh.setText("Refresh");
        refresh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 452, 87, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MASTER PEMINJAMAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 35, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("No Peminjaman");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 104, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("APLIKASI PERPUSTAKAAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 14));

        tf_nama.setEditable(false);
        tf_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_nama.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 170, 220, 30));

        tf_no_telp.setEditable(false);
        tf_no_telp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_no_telp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_no_telp.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 242, 220, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("No Telepon");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 248, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(":");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 248, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 213, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Kelas");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 213, -1, -1));

        tf_kelas.setEditable(false);
        tf_kelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_kelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_kelas.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 206, 220, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("No Induk Buku");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 104, -1, -1));

        tf_judul_buku.setEditable(false);
        tf_judul_buku.setColumns(20);
        tf_judul_buku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_judul_buku.setRows(5);
        tf_judul_buku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jScrollPane1.setViewportView(tf_judul_buku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 134, 220, 98));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText(":");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 104, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Judul Buku");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 142, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Pengarang");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 248, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText(":");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 248, -1, -1));

        tf_pengarang.setEditable(false);
        tf_pengarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_pengarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_pengarang.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 242, 220, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText(":");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 142, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Jumlah Buku");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 104, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText(":");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 104, -1, -1));

        tf_jumlah_buku.setEditable(false);
        tf_jumlah_buku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_jumlah_buku.setText("0");
        tf_jumlah_buku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_jumlah_buku.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_jumlah_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 98, 134, 30));

        tf_tersedia.setEditable(false);
        tf_tersedia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tersedia.setText("0");
        tf_tersedia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_tersedia.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_tersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 134, 134, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText(":");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 141, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Tersedia");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 141, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Keluar");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 176, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText(":");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 176, -1, -1));

        tf_keluar.setEditable(false);
        tf_keluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_keluar.setText("0");
        tf_keluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_keluar.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 134, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Batas Pengembalian");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 495, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Jumlah Buku Dipinjam");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 530, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText(":");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 530, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText(":");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 495, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText(":");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 458, -1, -1));

        tf_tanggal_pinjam.setEditable(false);
        tf_tanggal_pinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tanggal_pinjam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_tanggal_pinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_tanggal_pinjam.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_tanggal_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 452, 150, 30));

        tf_batas_pengembalian.setEditable(false);
        tf_batas_pengembalian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_batas_pengembalian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_batas_pengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_batas_pengembalian.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_batas_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 488, 150, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Tanggal Pinjam");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 458, -1, -1));

        tf_jumlah_buku_dipinjam.setEditable(false);
        tf_jumlah_buku_dipinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_jumlah_buku_dipinjam.setText("0");
        tf_jumlah_buku_dipinjam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_jumlah_buku_dipinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_jumlah_buku_dipinjam.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_jumlah_buku_dipinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 524, 150, 30));

        tf_nib.setEditable(true);
        tf_nib.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        tf_nib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nibActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nib, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 98, 220, 30));

        tf_nis.setEditable(true);
        tf_nis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        tf_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nisActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 134, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon6.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 64));

        keluar.setText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 452, 87, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Form Master 2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        if(jTable1.getRowCount() == 3){
            JOptionPane.showMessageDialog(null, "Batas jumlah buku dipinjam : 3");
        }else{
            if(tf_nama.getText().isEmpty()){
                tf_nis.requestFocus();
            }else{
                if(tf_judul_buku.getText().isEmpty()){
                    tf_nib.requestFocus();
                }else{
                    String[] tabel_master={tf_nib.getSelectedItem().toString(),tf_judul_buku.getText(),tf_pengarang.getText(),tf_jumlah_buku.getText(),tf_tersedia.getText(),tf_keluar.getText()};
                    tabel.addRow(tabel_master);

                    tf_nib.setSelectedItem("-");
                    tf_judul_buku.setText(null);
                    tf_pengarang.setText(null);
                    tf_jumlah_buku.setText("0");
                    tf_tersedia.setText("0");
                    tf_keluar.setText("0");
                    
                    tf_jumlah_buku_dipinjam.setText(""+jTable1.getRowCount());
                }
            }
        }        
    }//GEN-LAST:event_tambahActionPerformed

    private void tf_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nisActionPerformed
        tampil_data_anggota();
    }//GEN-LAST:event_tf_nisActionPerformed

    private void tf_nibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nibActionPerformed
        tampil_data_buku();
    }//GEN-LAST:event_tf_nibActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        empty_field();
        penomoran_otomatis();
        tampilTanggal();
        tf_nis.setSelectedItem("-");
    }//GEN-LAST:event_refreshActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if(tf_nama.getText().isEmpty() || tf_jumlah_buku_dipinjam.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Peminjaman Terlebih Dahulu !");
        }else{
            fungsi_simpan_data();
            fungsi_update_jumlah_buku();
            refreshActionPerformed(evt);
        }        
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int tabel_data = jTable1.getSelectedRow();        
        if(String.valueOf(tabel_data).equals("-1")){
            JOptionPane.showMessageDialog(this, "Pilih Daftar Yang Akan Dihapus !");
        }else
        {
            tabel.removeRow(tabel_data);
            tf_nis.requestFocus();
        }
        tf_jumlah_buku_dipinjam.setText(""+jTable1.getRowCount());
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_5_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_5_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_5_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_5_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_5_Peminjaman dialog = new Form_5_Peminjaman(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton refresh;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tf_batas_pengembalian;
    private javax.swing.JTextArea tf_judul_buku;
    private javax.swing.JTextField tf_jumlah_buku;
    private javax.swing.JTextField tf_jumlah_buku_dipinjam;
    private javax.swing.JTextField tf_kelas;
    private javax.swing.JTextField tf_keluar;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JComboBox tf_nib;
    private javax.swing.JComboBox tf_nis;
    private javax.swing.JTextField tf_no_peminjaman;
    private javax.swing.JTextField tf_no_telp;
    private javax.swing.JTextField tf_pengarang;
    private javax.swing.JTextField tf_tanggal_pinjam;
    private javax.swing.JTextField tf_tersedia;
    // End of variables declaration//GEN-END:variables
    
    private void empty_field() {
        tf_no_peminjaman.setText(null);
        tf_nis.setSelectedItem("-");
        tf_nama.setText(null);
        tf_kelas.setText(null);
        tf_no_telp.setText(null);
        tf_nib.setSelectedItem("-");
        tf_judul_buku.setText(null);
        tf_pengarang.setText(null);
        tf_jumlah_buku.setText("0");
        tf_tersedia.setText("0");
        tf_keluar.setText("0");
        tf_tanggal_pinjam.setText(null);
        tf_batas_pengembalian.setText(null);
        tf_jumlah_buku_dipinjam.setText("0");
        
        int data = jTable1.getRowCount();
        for(int i=0;i<data;i++){
            tabel.removeRow(0);
        }
    }
    
    private void tampil_nis_dan_nib() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_2_anggota ORDER BY nis ASC");
            while(re.next()){
                tf_nis.addItem(re.getString("nis"));
            }
            ResultSet re1=koneksi.createStatement().executeQuery("SELECT * FROM tbl_3_buku ORDER BY no_induk_buku ASC");
            while(re1.next()){
                tf_nib.addItem(re1.getString("no_induk_buku"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil NIS & NIB !");
        }
    }

    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
    
    private void penomoran_otomatis() {
        int no_no_peminjaman=0;
        String temp_no_peminjaman="";
        try {
            koneksi();
            String sql = "select no_peminjaman from tbl_4_transaksi_peminjaman order by no_peminjaman desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_no_peminjaman = res.getString(1);                
                String nomor_blkg = temp_no_peminjaman.substring(4,7);
                no_no_peminjaman=Integer.parseInt(nomor_blkg);
            }
                        
            no_no_peminjaman++;
            String nilai=String.valueOf(no_no_peminjaman);                      
            if(nilai.length()==1){
                tf_no_peminjaman.setText("PJM000"+no_no_peminjaman);
            }else
            if(nilai.length()==2){
                tf_no_peminjaman.setText("PJM00"+no_no_peminjaman);
            }else
            if(nilai.length()==3){
                tf_no_peminjaman.setText("PJM0"+no_no_peminjaman);
            }else
            if(nilai.length()==4){
                tf_no_peminjaman.setText("PJM"+no_no_peminjaman);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }

    private void fungsi_simpan_data() {
        boolean simpan_transaksi=false, simpan_detil=false;
        try {
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            koneksi.createStatement().executeUpdate("INSERT INTO tbl_4_transaksi_peminjaman VALUES('"+tf_no_peminjaman.getText()+"'"
            + ",'"+tf_nis.getSelectedItem()+"','"+tf_tanggal_pinjam.getText()+"','"+tf_batas_pengembalian.getText()+"'"
            + ",'"+tf_jumlah_buku_dipinjam.getText()+"')");
            simpan_transaksi = true;
        } catch (SQLException ex) {
            simpan_transaksi = false;
        }
        
        int jumlah_data = jTable1.getRowCount();
        for(int i=0;i<jumlah_data;i++){
            try {
                Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
                koneksi.createStatement().executeUpdate("INSERT INTO tbl_5_detil_peminjaman VALUES('"+tf_no_peminjaman.getText()+"'"
                + ",'"+tabel.getValueAt(i, 0)+"','1','Dipinjam')");
                simpan_detil = true;
            } catch (SQLException ex) {
                simpan_detil = false;
            }
        }
        
        if(simpan_transaksi && simpan_detil){
            JOptionPane.showMessageDialog(null, "Data Peminjaman Disimpan");
        }else{
            JOptionPane.showMessageDialog(null, "Data Peminjaman Gagal Disimpan");
            if(simpan_detil == false){
                JOptionPane.showMessageDialog(null, "Simpan Detil Gagal");
            }else
            if(simpan_transaksi == false){
                JOptionPane.showMessageDialog(null, "Simpan Transaksi Gagal");
            }else{
                JOptionPane.showMessageDialog(null, "Simpan Gagal");
            }
        }
    }

    private void aturKolom() {
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(110);        
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(355); 
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(250);
        column = jTable1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(100);
        column = jTable1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(100);
        column = jTable1.getColumnModel().getColumn(5); 
        column.setPreferredWidth(100);
    }

    private void aturFokus() {
        tf_nis.setNextFocusableComponent(tf_nib);
        tf_nib.setNextFocusableComponent(tf_nis);
    }
    
    private void tampilTanggal() {
        SimpleDateFormat sdfdate = new SimpleDateFormat("yyyy-MM-dd");
        Date tanggal_sekarang = new Date();
        tf_tanggal_pinjam.setText(sdfdate.format(tanggal_sekarang));
        
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, 6);
        Date tigaharilagi = cal.getTime();
        tf_batas_pengembalian.setText(sdfdate.format(tigaharilagi));
    }

    private void tampil_data_anggota() {
        boolean tanggunan_peminjaman = false;
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_4_transaksi_peminjaman WHERE nis = '"+tf_nis.getSelectedItem()+"'");
            while(re.next()){
                ResultSet re1=koneksi.createStatement().executeQuery("SELECT * FROM tbl_5_detil_peminjaman WHERE no_peminjaman = '"+re.getString("no_peminjaman")+"' AND status ='Dipinjam'");
                if(re1.next()){
                    tanggunan_peminjaman = true;
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Data Anggota !");
        }
        
        if(tanggunan_peminjaman){
            JOptionPane.showMessageDialog(null, "Anggota Masih Memiliki \nTanggungan Peminjaman Buku!");
        }else{
            try {
                com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
                ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_2_anggota WHERE nis = '"+tf_nis.getSelectedItem()+"'");
                while(re.next()){
                    tf_nama.setText(re.getString(2));
                    tf_kelas.setText(re.getString(3));
                    tf_no_telp.setText(re.getString(4));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Data Anggota !");
            }
        }        
    }

    private void tampil_data_buku() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_3_buku WHERE no_induk_buku = '"+tf_nib.getSelectedItem()+"'");
            while(re.next()){
                tf_judul_buku.setText(re.getString(3));
                tf_pengarang.setText(re.getString(4));
                tf_jumlah_buku.setText(re.getString(7));
                tf_tersedia.setText(re.getString(8));
                tf_keluar.setText(re.getString(9));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Data Buku !");
        }
    }

    private void fungsi_update_jumlah_buku() {
        int jumlah_data = jTable1.getRowCount();
        for(int i=0;i<jumlah_data;i++){
            int jumlah_buku=0, tersedia=0, keluar=0;
            try {
                com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
                ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_3_buku WHERE no_induk_buku = '"+tabel.getValueAt(i, 0)+"'");
                while(re.next()){
                    jumlah_buku = Integer.parseInt(re.getString("jumlah"));
                    keluar = Integer.parseInt(re.getString("keluar")) + 1;
                    tersedia = jumlah_buku - keluar;
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Baca Data Jumlah Buku !");
            }
            
            try {
                Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
                koneksi.createStatement().executeUpdate("UPDATE tbl_3_buku SET jumlah='"+jumlah_buku+"',tersedia='"+tersedia+"',keluar='"+keluar+"' "
                + "WHERE no_induk_buku = '"+tabel.getValueAt(i, 0)+"'");
            } catch (SQLException ex1) {
               JOptionPane.showMessageDialog(this, "Data Jumlah Gagal Diubah !");
            }
        }
    }
}
