/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form_master;

import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 */
public class Form_9_Detil_Peminjaman extends javax.swing.JDialog {
    private final DefaultTableModel tabel;
    Boolean fungsi_simpan=false, fungsi_ubah=false;
    public Statement stt;
    public Connection con;
    private TableColumn column;
    public static String public_no_peminjaman="";

    /**
     * Creates new form Form_1_Kategori
     */
    public Form_9_Detil_Peminjaman(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String[] judul={"No Induk Buku","Judul Buku","Pengarang","Jumlah Buku","Tersedia","Keluar","Status"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        aturKolom();
        tampil_data();
        ImageIcon ico = new ImageIcon("src/gambar/icon_item.png");
        setIconImage(ico.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_no_peminjaman = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_kelas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tf_tanggal_pinjam = new javax.swing.JTextField();
        tf_batas_pengembalian = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tf_jumlah_buku_dipinjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_nis = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detil Peminjaman");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NIS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 141, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama Anggota");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 177, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 178, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText(":");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 141, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(":");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 104, -1, -1));

        tf_no_peminjaman.setEditable(false);
        tf_no_peminjaman.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_no_peminjaman.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_no_peminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_no_peminjaman.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_no_peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 98, 220, 30));

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(17);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 247, 1021, 195));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DETIL PEMINJAMAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 35, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("No Peminjaman");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 104, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("APLIKASI PERPUSTAKAAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 14));

        tf_nama.setEditable(false);
        tf_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_nama.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 170, 220, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 213, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Kelas");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 213, -1, -1));

        tf_kelas.setEditable(false);
        tf_kelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_kelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_kelas.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 206, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Batas Pengembalian");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 495, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Jumlah Buku Dipinjam");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 530, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText(":");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 530, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText(":");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 495, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText(":");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 458, -1, -1));

        tf_tanggal_pinjam.setEditable(false);
        tf_tanggal_pinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tanggal_pinjam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_tanggal_pinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_tanggal_pinjam.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_tanggal_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 452, 150, 30));

        tf_batas_pengembalian.setEditable(false);
        tf_batas_pengembalian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_batas_pengembalian.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_batas_pengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_batas_pengembalian.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_batas_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 488, 150, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Tanggal Pinjam");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 458, -1, -1));

        tf_jumlah_buku_dipinjam.setEditable(false);
        tf_jumlah_buku_dipinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_jumlah_buku_dipinjam.setText("0");
        tf_jumlah_buku_dipinjam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_jumlah_buku_dipinjam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tf_jumlah_buku_dipinjam.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_jumlah_buku_dipinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 524, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon6.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 64));

        tf_nis.setEditable(false);
        tf_nis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_nis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        tf_nis.setMargin(new java.awt.Insets(0, 3, 0, 3));
        getContentPane().add(tf_nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 134, 220, 30));

        keluar.setText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keluar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 87, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Form Master 2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_9_Detil_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_9_Detil_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_9_Detil_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_9_Detil_Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_9_Detil_Peminjaman dialog = new Form_9_Detil_Peminjaman(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField tf_batas_pengembalian;
    private javax.swing.JTextField tf_jumlah_buku_dipinjam;
    private javax.swing.JTextField tf_kelas;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_nis;
    private javax.swing.JTextField tf_no_peminjaman;
    private javax.swing.JTextField tf_tanggal_pinjam;
    // End of variables declaration//GEN-END:variables
           
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }

    private void aturKolom() {
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);        
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(360); 
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(195);
        column = jTable1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(90);
        column = jTable1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(90);
        column = jTable1.getColumnModel().getColumn(5); 
        column.setPreferredWidth(90);
        column = jTable1.getColumnModel().getColumn(6); 
        column.setPreferredWidth(90);
    }

    private void tampil_data() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_4_transaksi_peminjaman WHERE no_peminjaman = '"+public_no_peminjaman+"'");
            while(re.next()){
                ResultSet re1=koneksi.createStatement().executeQuery("SELECT * FROM tbl_2_anggota WHERE nis = '"+re.getString("nis")+"'");
                while(re1.next()){
                    tf_no_peminjaman.setText(public_no_peminjaman);
                    tf_nis.setText(re1.getString("nis"));
                    tf_nama.setText(re1.getString("nama_anggota"));
                    tf_kelas.setText(re1.getString("kelas"));
                    tf_tanggal_pinjam.setText(re.getString("tanggal_pinjam"));
                    tf_batas_pengembalian.setText(re.getString("batas_pengembalian"));
                    tf_jumlah_buku_dipinjam.setText(re.getString("total_buku_dipinjam"));
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Data !");
        }
        
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
            tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tbl_5_detil_peminjaman WHERE no_peminjaman = '"+public_no_peminjaman+"'");
            while(re.next()){                
                ResultSet re1=koneksi.createStatement().executeQuery("SELECT * FROM tbl_3_buku WHERE no_induk_buku = '"+re.getString("no_induk_buku")+"'");
                while(re1.next()){                
                    String[] tabel_master={re.getString(2),re1.getString(3),re1.getString(4),re1.getString(7),re1.getString(8),re1.getString(9),re.getString(4)};
                    tabel.addRow(tabel_master);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }
}
