/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package si_perpustakaan;
import form_cetak.Form_1_Cetak_Peminjaman;
import form_cetak.Form_2_Cetak_Pengembalian;
import form_master.Form_1_Pengguna;
import form_master.Form_2_Anggota;
import form_master.Form_3_Kategori_Buku;
import form_master.Form_4_Buku;
import form_master.Form_5_Peminjaman;
import form_master.Form_6_Pengembalian;
import form_master.Form_7_Data_Peminjaman;
import form_master.Form_8_Data_Pengembalian;
import form_pengaturan.Form_1_Ubah_Password;
import form_pengaturan.Form_2_Denda;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 */
public class Form_2_Menu_Utama extends javax.swing.JFrame {
    private Form_1_Login Form_1_Login;
    public static String public_status="", public_nama="", public_admin="";
    
    /**
     * Creates new form Form_2_Menu_Utama
     */
    public Form_2_Menu_Utama() {
        initComponents();
        hak_akses();
        ImageIcon ico = new ImageIcon("src/gambar/icon_item.png");
        setIconImage(ico.getImage());
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        master_pengguna = new javax.swing.JMenuItem();
        master_anggota = new javax.swing.JMenuItem();
        master_buku = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        sirkulasi_peminjaman = new javax.swing.JMenuItem();
        sirkulasi_pengembalian = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        data_peminjaman = new javax.swing.JMenuItem();
        data_pengembalian = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        laporan_anggota = new javax.swing.JMenuItem();
        laporan_buku = new javax.swing.JMenuItem();
        laporan_peminjaman = new javax.swing.JMenuItem();
        laporan_pengembalian = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        pengaturan_ubah_password = new javax.swing.JMenuItem();
        pengaturan_denda = new javax.swing.JMenuItem();
        pengaturan_kategori_buku = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APLIKASI PERPUSTAKAAN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Form_2_Menu_Utama.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Master");

        master_pengguna.setText("Master Admin");
        master_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_penggunaActionPerformed(evt);
            }
        });
        jMenu1.add(master_pengguna);

        master_anggota.setText("Master Anggota");
        master_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_anggotaActionPerformed(evt);
            }
        });
        jMenu1.add(master_anggota);

        master_buku.setText("Master Buku");
        master_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_bukuActionPerformed(evt);
            }
        });
        jMenu1.add(master_buku);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sirkulasi");

        sirkulasi_peminjaman.setText("Sirkulasi Peminjaman");
        sirkulasi_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sirkulasi_peminjamanActionPerformed(evt);
            }
        });
        jMenu2.add(sirkulasi_peminjaman);

        sirkulasi_pengembalian.setText("Sirkulasi Pengembalian");
        sirkulasi_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sirkulasi_pengembalianActionPerformed(evt);
            }
        });
        jMenu2.add(sirkulasi_pengembalian);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Data");

        data_peminjaman.setText("Data Peminjaman");
        data_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_peminjamanActionPerformed(evt);
            }
        });
        jMenu3.add(data_peminjaman);

        data_pengembalian.setText("Data Pengembalian");
        data_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_pengembalianActionPerformed(evt);
            }
        });
        jMenu3.add(data_pengembalian);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Laporan");

        laporan_anggota.setText("Laporan Data Anggota");
        laporan_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_anggotaActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_anggota);

        laporan_buku.setText("Laporan Data Buku");
        laporan_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_bukuActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_buku);

        laporan_peminjaman.setText("Laporan Data Peminjaman");
        laporan_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_peminjamanActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_peminjaman);

        laporan_pengembalian.setText("Laporan Data Pengembalian");
        laporan_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_pengembalianActionPerformed(evt);
            }
        });
        jMenu7.add(laporan_pengembalian);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Pengaturan");

        pengaturan_ubah_password.setText("Ubah Password");
        pengaturan_ubah_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturan_ubah_passwordActionPerformed(evt);
            }
        });
        jMenu4.add(pengaturan_ubah_password);

        pengaturan_denda.setText("Denda");
        pengaturan_denda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturan_dendaActionPerformed(evt);
            }
        });
        jMenu4.add(pengaturan_denda);

        pengaturan_kategori_buku.setText("Kategori Buku");
        pengaturan_kategori_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturan_kategori_bukuActionPerformed(evt);
            }
        });
        jMenu4.add(pengaturan_kategori_buku);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Keluar");

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Form_1_Login = new Form_1_Login();
        Form_1_Login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void master_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_master_penggunaActionPerformed
        Form_1_Pengguna frameform = new Form_1_Pengguna(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_master_penggunaActionPerformed

    private void master_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_master_anggotaActionPerformed
        Form_2_Anggota frameform = new Form_2_Anggota(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_master_anggotaActionPerformed

    private void pengaturan_kategori_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturan_kategori_bukuActionPerformed
        Form_3_Kategori_Buku frameform = new Form_3_Kategori_Buku(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_pengaturan_kategori_bukuActionPerformed

    private void master_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_master_bukuActionPerformed
        Form_4_Buku frameform = new Form_4_Buku(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_master_bukuActionPerformed

    private void pengaturan_ubah_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturan_ubah_passwordActionPerformed
        Form_1_Ubah_Password frameform = new Form_1_Ubah_Password(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_pengaturan_ubah_passwordActionPerformed

    private void pengaturan_dendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturan_dendaActionPerformed
        Form_2_Denda frameform = new Form_2_Denda(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_pengaturan_dendaActionPerformed

    private void sirkulasi_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sirkulasi_peminjamanActionPerformed
        Form_5_Peminjaman frameform = new Form_5_Peminjaman(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_sirkulasi_peminjamanActionPerformed

    private void sirkulasi_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sirkulasi_pengembalianActionPerformed
        Form_6_Pengembalian frameform = new Form_6_Pengembalian(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_sirkulasi_pengembalianActionPerformed

    private void data_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_peminjamanActionPerformed
        Form_7_Data_Peminjaman frameform = new Form_7_Data_Peminjaman(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_data_peminjamanActionPerformed

    private void data_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_pengembalianActionPerformed
        Form_8_Data_Pengembalian frameform = new Form_8_Data_Pengembalian(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_data_pengembalianActionPerformed

    private void laporan_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_anggotaActionPerformed
        try {
            String NamaFile = "src/laporan/Laporan_1_Data_Anggota.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            HashMap hash = new HashMap();
            File file = new File(NamaFile);
            //Mengambil parameter dari ireport
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");
            //viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak "+e);
        }
    }//GEN-LAST:event_laporan_anggotaActionPerformed

    private void laporan_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_bukuActionPerformed
        try {
            String NamaFile = "src/laporan/Laporan_2_Data_Buku.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/si_perpus","root","");
            HashMap hash = new HashMap();
            File file = new File(NamaFile);
            //Mengambil parameter dari ireport
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, hash, koneksi);
            JRViewer aViewer = new JRViewer(jasperPrint);
            JDialog viewer = new JDialog();
            viewer.setTitle(".: Jasper Report :.");
            //viewer.setAlwaysOnTop(true);
            viewer.getContentPane().add(aViewer);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            viewer.setBounds(0,0,screenSize.width, screenSize.height);
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Cetak "+e);
        }
    }//GEN-LAST:event_laporan_bukuActionPerformed

    private void laporan_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_peminjamanActionPerformed
        Form_1_Cetak_Peminjaman frameform = new Form_1_Cetak_Peminjaman(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_laporan_peminjamanActionPerformed

    private void laporan_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_pengembalianActionPerformed
        Form_2_Cetak_Pengembalian frameform = new Form_2_Cetak_Pengembalian(this, false);
        frameform.setVisible(true);
    }//GEN-LAST:event_laporan_pengembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_2_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_2_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_2_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_2_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_2_Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem data_peminjaman;
    private javax.swing.JMenuItem data_pengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem laporan_anggota;
    private javax.swing.JMenuItem laporan_buku;
    private javax.swing.JMenuItem laporan_peminjaman;
    private javax.swing.JMenuItem laporan_pengembalian;
    private javax.swing.JMenuItem master_anggota;
    private javax.swing.JMenuItem master_buku;
    private javax.swing.JMenuItem master_pengguna;
    private javax.swing.JMenuItem pengaturan_denda;
    private javax.swing.JMenuItem pengaturan_kategori_buku;
    private javax.swing.JMenuItem pengaturan_ubah_password;
    private javax.swing.JMenuItem sirkulasi_peminjaman;
    private javax.swing.JMenuItem sirkulasi_pengembalian;
    // End of variables declaration//GEN-END:variables

    private void hak_akses() {
        ActionListener taskPerformer = new ActionListener() {

        public void actionPerformed(ActionEvent evt) {            
            if(public_status.equals("Admin")){
                
            }else
            if(public_status.equals("Pegawai")){
                
            }
        }        
        };
        new Timer(1000, taskPerformer).start();
    }
}
